# Streamlit Cloud Secrets Configuration
# Copy this file to your Streamlit Cloud app settings → Secrets
# Remove the # comment character before each line

CHUTES_API_TOKEN="cpk_88b9f8efff0f47bb9803ba9155721490.586556b01e0c5b03aec4f472ac43532f.P7BxRqCtlWEFO2W715fkH2VuBmGFqxFh"
